-- ============================================================================
-- Capstone Animal Rescue Platform - Database Schema
-- Version: 1.0.0
-- 
-- This script creates all required tables for the animal rescue platform.
-- Run this in Supabase SQL Editor or via `supabase db push` for new environments.
-- 
-- Tables: animals, medical_records, users, roles, user_roles
-- ============================================================================

-- ============================================================================
-- ANIMALS TABLE
-- Core catalog of animals available for adoption
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.animals (
    aid SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    species VARCHAR(50),
    size VARCHAR(20) CHECK (size IN ('small', 'medium', 'large', 'extra_large')),
    gender VARCHAR(20) CHECK (gender IN ('male', 'female', 'unknown')),
    status VARCHAR(20) DEFAULT 'available' CHECK (status IN ('available', 'adopted', 'pending', 'fostered', 'medical_hold')),
    image_url TEXT,
    image_object_key TEXT,
    tags TEXT[] DEFAULT '{}',
    microchip_id VARCHAR(50),
    is_sterilized BOOLEAN DEFAULT false,
    estimated_age VARCHAR(50),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    record_id INTEGER
);

-- Index for common queries
CREATE INDEX IF NOT EXISTS idx_animals_status ON public.animals(status);
CREATE INDEX IF NOT EXISTS idx_animals_species ON public.animals(species);
CREATE INDEX IF NOT EXISTS idx_animals_tags ON public.animals USING GIN(tags);
CREATE INDEX IF NOT EXISTS idx_animals_microchip_id ON public.animals(microchip_id);

COMMENT ON TABLE public.animals IS 'Animal catalog with adoption status and attributes';

-- ============================================================================
-- MEDICAL RECORDS TABLE
-- Treatment history linked to animals
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.medical_records (
    record_id SERIAL PRIMARY KEY,
    aid INTEGER REFERENCES public.animals(aid) ON DELETE CASCADE,
    medicine_name VARCHAR(100),
    date_given TIMESTAMPTZ,
    vet_name VARCHAR(100),
    notes TEXT,
    record_type VARCHAR(50) CHECK (record_type IN ('vacunación','desparasitación','esterilización','tratamiento','examen','cirugía')),
    next_due_date TIMESTAMPTZ,
    dosage VARCHAR(100),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add foreign key from animals to medical_records (optional reference)
ALTER TABLE public.animals 
    ADD CONSTRAINT animals_record_id_fkey 
    FOREIGN KEY (record_id) REFERENCES public.medical_records(record_id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_medical_records_aid ON public.medical_records(aid);
CREATE INDEX IF NOT EXISTS idx_medical_records_record_type ON public.medical_records(record_type);
CREATE INDEX IF NOT EXISTS idx_medical_records_next_due_date ON public.medical_records(next_due_date);

COMMENT ON TABLE public.medical_records IS 'Medical treatment history for animals';

-- ============================================================================
-- USERS TABLE
-- User accounts for future auth integration
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.users (
    uid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    role TEXT
);

COMMENT ON TABLE public.users IS 'User accounts for authentication and authorization';

-- ============================================================================
-- ROLES TABLE
-- RBAC role definitions
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.roles (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE public.roles IS 'Core RBAC roles for access control';

-- Insert default roles
INSERT INTO public.roles (name, description) VALUES
    ('admin', 'Full system access - manage animals, users, and settings'),
    ('helper', 'Can assist with animal care and view records')
ON CONFLICT (name) DO NOTHING;

-- ============================================================================
-- USER_ROLES TABLE
-- Junction table mapping users to their assigned roles
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.user_roles (
    id SERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(uid) ON DELETE CASCADE,
    role_id INTEGER NOT NULL REFERENCES public.roles(id) ON DELETE CASCADE,
    assigned_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, role_id)
);

CREATE INDEX IF NOT EXISTS idx_user_roles_user_id ON public.user_roles(user_id);
CREATE INDEX IF NOT EXISTS idx_user_roles_role_id ON public.user_roles(role_id);

COMMENT ON TABLE public.user_roles IS 'Junction table mapping users to their assigned roles';

-- ============================================================================
-- ROW LEVEL SECURITY (RLS)
-- Enable RLS on all tables for future auth integration
-- ============================================================================
ALTER TABLE public.animals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.medical_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- RLS POLICIES
-- Basic policies allowing service_role full access
-- Additional policies for authenticated users can be added later
-- ============================================================================

-- Animals: Allow public read, authenticated write
CREATE POLICY IF NOT EXISTS "Allow public read access on animals" 
    ON public.animals FOR SELECT 
    USING (true);

CREATE POLICY IF NOT EXISTS "Allow service role full access on animals" 
    ON public.animals FOR ALL 
    USING (auth.role() = 'service_role');

-- Medical Records: Service role only (contains sensitive veterinary data)
CREATE POLICY IF NOT EXISTS "Allow service role read access on medical_records"
    ON public.medical_records FOR SELECT
    USING (auth.role() = 'service_role');

CREATE POLICY IF NOT EXISTS "Allow service role full access on medical_records"
    ON public.medical_records FOR ALL
    USING (auth.role() = 'service_role');

-- Users: Service role only
CREATE POLICY IF NOT EXISTS "Allow service role full access on users" 
    ON public.users FOR ALL 
    USING (auth.role() = 'service_role');

-- Roles: Public read, service role write
CREATE POLICY IF NOT EXISTS "Allow public read access on roles" 
    ON public.roles FOR SELECT 
    USING (true);

CREATE POLICY IF NOT EXISTS "Allow service role full access on roles" 
    ON public.roles FOR ALL 
    USING (auth.role() = 'service_role');

-- User Roles: Service role only
CREATE POLICY IF NOT EXISTS "Allow service role full access on user_roles" 
    ON public.user_roles FOR ALL 
    USING (auth.role() = 'service_role');

-- ============================================================================
-- RPC FUNCTIONS
-- ============================================================================

CREATE OR REPLACE FUNCTION patch_animal_with_medical_records(
    p_aid INTEGER,
    p_animal_updates JSONB DEFAULT '{}'::JSONB,
    p_medical_records JSONB DEFAULT '[]'::JSONB
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY INVOKER
AS $$
DECLARE
    v_existing_animal public.animals%ROWTYPE;
    v_updated_animal public.animals%ROWTYPE;
    v_medical_record JSONB;
    v_record_id INTEGER;
BEGIN
    IF jsonb_typeof(COALESCE(p_animal_updates, '{}'::JSONB)) <> 'object' THEN
        RAISE EXCEPTION 'animal updates payload must be a JSON object';
    END IF;

    IF jsonb_typeof(COALESCE(p_medical_records, '[]'::JSONB)) <> 'array' THEN
        RAISE EXCEPTION 'medical records payload must be a JSON array';
    END IF;

    SELECT *
    INTO v_existing_animal
    FROM public.animals
    WHERE aid = p_aid
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Animal not found';
    END IF;

    IF COALESCE(p_animal_updates, '{}'::JSONB) = '{}'::JSONB THEN
        v_updated_animal := v_existing_animal;
    ELSE
        UPDATE public.animals
        SET
            name = CASE
                WHEN p_animal_updates ? 'name' THEN p_animal_updates->>'name'
                ELSE name
            END,
            description = CASE
                WHEN p_animal_updates ? 'description' THEN p_animal_updates->>'description'
                ELSE description
            END,
            species = CASE
                WHEN p_animal_updates ? 'species' THEN p_animal_updates->>'species'
                ELSE species
            END,
            size = CASE
                WHEN p_animal_updates ? 'size' THEN p_animal_updates->>'size'
                ELSE size
            END,
            gender = CASE
                WHEN p_animal_updates ? 'gender' THEN p_animal_updates->>'gender'
                ELSE gender
            END,
            status = CASE
                WHEN p_animal_updates ? 'status' THEN p_animal_updates->>'status'
                ELSE status
            END,
            image_object_key = CASE
                WHEN p_animal_updates ? 'image_object_key'
                    THEN NULLIF(p_animal_updates->>'image_object_key', '')
                ELSE image_object_key
            END,
            image_url = CASE
                WHEN p_animal_updates ? 'image_url' THEN NULLIF(p_animal_updates->>'image_url', '')
                ELSE image_url
            END,
            record_id = CASE
                WHEN p_animal_updates ? 'record_id'
                    THEN CASE
                        WHEN jsonb_typeof(p_animal_updates->'record_id') = 'null' THEN NULL
                        ELSE (p_animal_updates->>'record_id')::INTEGER
                    END
                ELSE record_id
            END,
            tags = CASE
                WHEN p_animal_updates ? 'tags'
                    THEN ARRAY(SELECT jsonb_array_elements_text(p_animal_updates->'tags'))
                ELSE tags
            END
        WHERE aid = p_aid
        RETURNING *
        INTO v_updated_animal;
    END IF;

    FOR v_medical_record IN
        SELECT value
        FROM jsonb_array_elements(COALESCE(p_medical_records, '[]'::JSONB))
    LOOP
        IF v_medical_record ? 'record_id' THEN
            IF jsonb_typeof(v_medical_record->'record_id') = 'null' THEN
                RAISE EXCEPTION 'Invalid medical record record_id.';
            END IF;

            v_record_id := (v_medical_record->>'record_id')::INTEGER;

            IF NOT EXISTS (
                SELECT 1
                FROM public.medical_records
                WHERE record_id = v_record_id
                  AND aid = p_aid
            ) THEN
                RAISE EXCEPTION 'Medical record % does not belong to animal %.',
                    v_record_id,
                    p_aid;
            END IF;
        END IF;
    END LOOP;

    DELETE FROM public.medical_records
    WHERE aid = p_aid
      AND record_id NOT IN (
          SELECT (value->>'record_id')::INTEGER
          FROM jsonb_array_elements(COALESCE(p_medical_records, '[]'::JSONB))
          WHERE value ? 'record_id'
      );

    FOR v_medical_record IN
        SELECT value
        FROM jsonb_array_elements(COALESCE(p_medical_records, '[]'::JSONB))
    LOOP
        IF v_medical_record ? 'record_id' THEN
            UPDATE public.medical_records
            SET
                record_type = CASE
                    WHEN v_medical_record ? 'record_type'
                        THEN NULLIF(v_medical_record->>'record_type', '')
                    ELSE record_type
                END,
                date_given = CASE
                    WHEN v_medical_record ? 'date_given'
                        THEN CASE
                            WHEN jsonb_typeof(v_medical_record->'date_given') = 'null' THEN NULL
                            ELSE (v_medical_record->>'date_given')::TIMESTAMPTZ
                        END
                    ELSE date_given
                END,
                vet_name = CASE
                    WHEN v_medical_record ? 'vet_name'
                        THEN CASE
                            WHEN jsonb_typeof(v_medical_record->'vet_name') = 'null' THEN NULL
                            ELSE NULLIF(v_medical_record->>'vet_name', '')
                        END
                    ELSE vet_name
                END,
                notes = CASE
                    WHEN v_medical_record ? 'notes'
                        THEN CASE
                            WHEN jsonb_typeof(v_medical_record->'notes') = 'null' THEN NULL
                            ELSE NULLIF(v_medical_record->>'notes', '')
                        END
                    ELSE notes
                END
            WHERE record_id = (v_medical_record->>'record_id')::INTEGER
              AND aid = p_aid;
        ELSE
            INSERT INTO public.medical_records (
                aid,
                record_type,
                date_given,
                vet_name,
                notes
            )
            VALUES (
                p_aid,
                CASE
                    WHEN v_medical_record ? 'record_type'
                        THEN NULLIF(v_medical_record->>'record_type', '')
                    ELSE NULL
                END,
                CASE
                    WHEN v_medical_record ? 'date_given'
                        THEN CASE
                            WHEN jsonb_typeof(v_medical_record->'date_given') = 'null' THEN NULL
                            ELSE (v_medical_record->>'date_given')::TIMESTAMPTZ
                        END
                    ELSE NULL
                END,
                CASE
                    WHEN v_medical_record ? 'vet_name'
                        THEN CASE
                            WHEN jsonb_typeof(v_medical_record->'vet_name') = 'null' THEN NULL
                            ELSE NULLIF(v_medical_record->>'vet_name', '')
                        END
                    ELSE NULL
                END,
                CASE
                    WHEN v_medical_record ? 'notes'
                        THEN CASE
                            WHEN jsonb_typeof(v_medical_record->'notes') = 'null' THEN NULL
                            ELSE NULLIF(v_medical_record->>'notes', '')
                        END
                    ELSE NULL
                END
            );
        END IF;
    END LOOP;

    RETURN jsonb_build_object(
        'animal',
        to_jsonb(v_updated_animal),
        'medical_records',
        COALESCE(
            (
                SELECT jsonb_agg(to_jsonb(mr) ORDER BY mr.record_id)
                FROM public.medical_records mr
                WHERE mr.aid = p_aid
            ),
            '[]'::JSONB
        )
    );
END;
$$;

GRANT EXECUTE ON FUNCTION patch_animal_with_medical_records(INTEGER, JSONB, JSONB)
    TO service_role;

-- ============================================================================
-- VERIFICATION QUERIES
-- Run these to verify successful setup:
-- 
-- SELECT COUNT(*) FROM public.animals;          -- Should return animal count
-- SELECT * FROM public.roles ORDER BY id;       -- Should return 2 roles
-- SELECT tablename, rowsecurity FROM pg_tables 
--   WHERE schemaname = 'public';                -- All should have RLS enabled
-- ============================================================================
