-- ============================================================================
-- Capstone Animal Rescue Platform - Database Schema
-- Version: 1.0.0
-- 
-- This script creates all required tables for the animal rescue platform.
-- Run this in Supabase SQL Editor or via `supabase db push` for new environments.
-- 
-- Tables: animals, medical_records, users, roles, user_roles
-- ============================================================================

-- ============================================================================
-- ANIMALS TABLE
-- Core catalog of animals available for adoption
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.animals (
    aid SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    species VARCHAR(50),
    size VARCHAR(20) CHECK (size IN ('small', 'medium', 'large', 'extra_large')),
    gender VARCHAR(20) CHECK (gender IN ('male', 'female', 'unknown')),
    status VARCHAR(20) DEFAULT 'available' CHECK (status IN ('available', 'adopted', 'pending', 'fostered', 'medical_hold')),
    image_url TEXT,
    image_object_key TEXT,
    tags TEXT[] DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    record_id INTEGER
);

-- Index for common queries
CREATE INDEX IF NOT EXISTS idx_animals_status ON public.animals(status);
CREATE INDEX IF NOT EXISTS idx_animals_species ON public.animals(species);
CREATE INDEX IF NOT EXISTS idx_animals_tags ON public.animals USING GIN(tags);

COMMENT ON TABLE public.animals IS 'Animal catalog with adoption status and attributes';

-- ============================================================================
-- MEDICAL RECORDS TABLE
-- Treatment history linked to animals
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.medical_records (
    record_id SERIAL PRIMARY KEY,
    aid INTEGER REFERENCES public.animals(aid) ON DELETE CASCADE,
    medicine_name VARCHAR(100),
    date_given TIMESTAMPTZ,
    vet_name VARCHAR(100),
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add foreign key from animals to medical_records (optional reference)
ALTER TABLE public.animals 
    ADD CONSTRAINT animals_record_id_fkey 
    FOREIGN KEY (record_id) REFERENCES public.medical_records(record_id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_medical_records_aid ON public.medical_records(aid);

COMMENT ON TABLE public.medical_records IS 'Medical treatment history for animals';

-- ============================================================================
-- USERS TABLE
-- User accounts for future auth integration
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.users (
    uid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    role TEXT
);

COMMENT ON TABLE public.users IS 'User accounts for authentication and authorization';

-- ============================================================================
-- ROLES TABLE
-- RBAC role definitions
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.roles (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE public.roles IS 'Core RBAC roles for access control';

-- Insert default roles
INSERT INTO public.roles (name, description) VALUES
    ('admin', 'Full system access - manage animals, users, and settings'),
    ('helper', 'Can assist with animal care and view records')
ON CONFLICT (name) DO NOTHING;

-- ============================================================================
-- USER_ROLES TABLE
-- Junction table mapping users to their assigned roles
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.user_roles (
    id SERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(uid) ON DELETE CASCADE,
    role_id INTEGER NOT NULL REFERENCES public.roles(id) ON DELETE CASCADE,
    assigned_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, role_id)
);

CREATE INDEX IF NOT EXISTS idx_user_roles_user_id ON public.user_roles(user_id);
CREATE INDEX IF NOT EXISTS idx_user_roles_role_id ON public.user_roles(role_id);

COMMENT ON TABLE public.user_roles IS 'Junction table mapping users to their assigned roles';

-- ============================================================================
-- ROW LEVEL SECURITY (RLS)
-- Enable RLS on all tables for future auth integration
-- ============================================================================
ALTER TABLE public.animals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.medical_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- RLS POLICIES
-- Basic policies allowing service_role full access
-- Additional policies for authenticated users can be added later
-- ============================================================================

-- Animals: Allow public read, authenticated write
CREATE POLICY IF NOT EXISTS "Allow public read access on animals" 
    ON public.animals FOR SELECT 
    USING (true);

CREATE POLICY IF NOT EXISTS "Allow service role full access on animals" 
    ON public.animals FOR ALL 
    USING (auth.role() = 'service_role');

-- Medical Records: Service role only
CREATE POLICY IF NOT EXISTS "Allow service role full access on medical_records" 
    ON public.medical_records FOR ALL 
    USING (auth.role() = 'service_role');

-- Users: Service role only
CREATE POLICY IF NOT EXISTS "Allow service role full access on users" 
    ON public.users FOR ALL 
    USING (auth.role() = 'service_role');

-- Roles: Public read, service role write
CREATE POLICY IF NOT EXISTS "Allow public read access on roles" 
    ON public.roles FOR SELECT 
    USING (true);

CREATE POLICY IF NOT EXISTS "Allow service role full access on roles" 
    ON public.roles FOR ALL 
    USING (auth.role() = 'service_role');

-- User Roles: Service role only
CREATE POLICY IF NOT EXISTS "Allow service role full access on user_roles" 
    ON public.user_roles FOR ALL 
    USING (auth.role() = 'service_role');

-- ============================================================================
-- VERIFICATION QUERIES
-- Run these to verify successful setup:
-- 
-- SELECT COUNT(*) FROM public.animals;          -- Should return animal count
-- SELECT * FROM public.roles ORDER BY id;       -- Should return 2 roles
-- SELECT tablename, rowsecurity FROM pg_tables 
--   WHERE schemaname = 'public';                -- All should have RLS enabled
-- ============================================================================
